### ISSUE TITLE
Add more resources including assistive technologies and other tools for accessibility auditing

### ISSUE THREAD

**Issue by laurenchamps** [codelikeagirlau/accessibility-resources#21]
I thought it would be useful to collect a list of assistive technologies (eg VoiceOver, NVDA) and links to tutorials for using them so as developers we can start using these tools on our sites. I think the more we get familiar with using these tools ourselves, the better we'll be at developing with accessibility at front of mind ✨  
I'll add to the README and this might also include separating out the Tools and Resources section into sub-sections grouped based on the type of tool/resource it is.

**Comment by laurenchamps** [comment]
Looks like only maintainers can assign issues... @sarahesbie would you mind assigning this to me? Thank you! 🌟

**Comment by wendy-ha18** [comment]
Oh if you commented on this issue that you would love to work on it, other contributors like me will avoid to do it :)

As a contributor we can create new issue and close issue as well, I'm not sure maintainer still need to assign issue for you or not, but if the purpose is to prevent duplicate/similar working ideas between contributors, I think simpler process (without the need of maintainer assigning issue) will be easier for us.
