### ISSUE TITLE
Create navigation functionality to access new pages

### ISSUE THREAD

**Issue by lulen11** [codelikeagirlau/accessibility-resources#33]
Without working on the styles, create the navigation so that we can access new pages from the frontend

**Comment by pra9patil** [comment]
What you want to say that only create html pages and link them with index.html page is it right @lulen11 
and if this is right will you please assign me this issue under hactoberfest23 I will create these pages and one text line like coming soon so you can add content in future is that ok ,
if you like this please assign me this issue 

thank you!

**Comment by lulen11** [comment]
hey @pra9patil , I think we've since had this issue resolved! Pull down `main` and take a look :) If you're keen to build on it further, you're v welcome to! Just create a new issue as I'm gonna close this one for now :)
